name: docs

on:
  push

permissions:
  actions: write

jobs:
  generate-docs:
    name: generate-docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Markdown autodocs
        uses: dineshsonachalam/markdown-autodocs@v1.0.3
        env:
          ACCESSTOKEN: ${{ secrets.GITHUB_TOKEN }}
