name: docs

on:
  push

jobs:
  generate-docs:
    name: generate-docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Markdown autodocs
        uses: dineshsonachalam/markdown-autodocs@v1.0.3
